---
name: JSON Linter
run-name: ${{ github.actor }} executed run JSON linter
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run JSON Lint
        env:
          REPORT_ONLY: true
          SHOW_ERRORS: true
          SHOW_SKIPPED: true
        run: bash pipeline.sh
