name: JSON Linter
run-name: ${{ github.actor }} executed run JSON linter
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    - name: Run JSON Lint
      run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)